version: '3'

services:
    sut:
        build: .
        command: npm test
        depends_on:
            - testdb
        links:
            - testdb
        environment:
            - DBDB
            - DBUSER
            - DBPWD
            - DBHOST=pgdbtest
    testdb:
        image: postgres
        hostname: pgdbtest
        ports:
            - 5432:5432
        environment:
            - PGDATA=/var/lib/postgresql/data/pgdata
            - POSTGRES_DB=${DBDB}
            - POSTGRES_USER=${DBUSER}
            - POSTGRES_PASSWORD=${DBPWD}
            - PGPASSWORD=${DBROOTPWD}
